name: Deploy api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      PROJECT_DIR: /root/projects/my_communify_api
      PM2_PROCESS: my_communify_backend

    steps:
      - name: Build and Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add /root/.ssh/duynguyenxdev

            # Load Node/NVM environment (Crucial for non-interactive SSH shells)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd ${{ env.PROJECT_DIR }}
            git reset --hard
            git pull origin ${{ github.ref_name }}
            npm install
            npm run build
            pm2 reload ${{ env.PM2_PROCESS }} --update-env || pm2 start dist/src/main.js --name "${{ env.PM2_PROCESS }}"
            pm2 save
